// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-10-26 23:14:18.142576 +0700 WIB m=+0.022199203

package docs

import (
	"bytes"
	"encoding/json"
	"os"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/history/+6281247930699": {
          "get": {
            "description": "",
            "summary": "HISTORY",
            "tags": [
              "CIMOL"
            ],
            "operationId": "HISTORY",
            "deprecated": false,
            "produces": [
              "application/json"
            ],
            "parameters": [],
            "responses": {
              "200": {
                "description": "",
                "schema": {
                  "type": "object"
                },
                "headers": {}
              }
            }
          }
        },
        "/id/ccdd2d3b-df6c-4cf7-b646-781b9bdaeeaf": {
          "get": {
            "description": "",
            "summary": "GET BY ID",
            "tags": [
              "CIMOL"
            ],
            "operationId": "GETBYID",
            "deprecated": false,
            "produces": [
              "application/json"
            ],
            "parameters": [],
            "responses": {
              "200": {
                "description": "",
                "schema": {
                  "type": "object"
                },
                "headers": {}
              }
            }
          }
        },
        "/sms": {
          "post": {
            "description": "",
            "summary": "SEND SMS",
            "tags": [
              "CIMOL"
            ],
            "operationId": "SENDSMS",
            "deprecated": false,
            "produces": [
              "application/json"
            ],
            "parameters": [
              {
                "name": "Body",
                "in": "body",
                "required": true,
                "schema": {
                  "$ref": "#/definitions/SENDSMSRequest"
                }
              },
              {
                "name": "Content-Type",
                "in": "header",
                "required": true,
                "type": "string"
              }
            ],
            "responses": {
              "200": {
                "description": "",
                "schema": {
                  "type": "object"
                },
                "headers": {}
              }
            }
          }
        },
        "/email": {
          "post": {
            "description": "",
            "summary": "SEND EMAIL",
            "tags": [
              "CIMOL"
            ],
            "operationId": "SENDEMAIL",
            "deprecated": false,
            "produces": [
              "application/json"
            ],
            "parameters": [
              {
                "name": "Body",
                "in": "body",
                "required": true,
                "schema": {
                  "$ref": "#/definitions/SENDEMAILRequest"
                }
              },
              {
                "name": "Content-Type",
                "in": "header",
                "required": true,
                "type": "string"
              }
            ],
            "responses": {
              "200": {
                "description": "",
                "schema": {
                  "type": "object"
                },
                "headers": {}
              }
            }
          }
        }
      },
      "definitions": {
        "SENDSMSRequest": {
          "title": "SENDSMSRequest",
          "example": {
            "type": "sms",
            "uuid": "01033d88-afc7-48d9-85af-27578aff0c73",
            "payload": {
              "otp": true,
              "msisdn": "081247930699",
              "text": "NEW DAEMON GOLANG SWITCHING TEST"
            }
          },
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "uuid": {
              "type": "string"
            },
            "payload": {
              "type": "object"
            }
          },
          "required": [
            "type",
            "uuid",
            "payload"
          ]
        },
        "SENDEMAILRequest": {
          "title": "SENDEMAILRequest",
          "example": {
            "uuid": "01033d88-afc7-48d9-85af-27578aff0e70",
            "type": "email",
            "payload": {
              "to": "meongbego@gmail.com",
              "from": "support@ralali.com",
              "subject": "Testing Email",
              "data": {
                "-header_text-": "Ralali",
                "-nama_buyer-": "testing",
                "-request_date-": "2020-02-10",
                "-header_information-": "Pembayaran SKU Anton Cubby",
                "-submission_date-": "2020-02-10"
              },
              "template_id": "1ffa0815-b100-4622-9106-3b1c16170b5b"
            }
          },
          "type": "object",
          "properties": {
            "uuid": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "payload": {
              "type": "object"
            }
          },
          "required": [
            "uuid",
            "type",
            "payload"
          ]
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "v0.8.0",
	Host:        os.Getenv("SWAGGER_SERVER_ADDRESS"),
	BasePath:    "/v1/notification",
	Schemes:     []string{},
	Title:       "CIMOL",
	Description: "CIMOL Notification Service",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
